theme: jekyll-theme-minimal
title: Özcan Türkmen
description: "<span style="text-align:center;">Senior Software Engineer/Architect</span>"
logo: "https://avatars1.githubusercontent.com/u/23320140?s=460&v=4"
show_downloads: false
