theme: jekyll-theme-minimal
title: <span style="text-align:center;">Özcan Türkmen</span>
description: Senior Software Engineer/Architect
logo: "https://avatars1.githubusercontent.com/u/23320140?s=460&v=4"
show_downloads: false
