theme: jekyll-theme-cayman
title: Özcan Türkmen
description: Bio
logo: https://avatars1.githubusercontent.com/u/23320140?s=460&v=4
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: 
